<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\..\CustomerService\CustomerService.Domain\CustomerService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Models\**" />
  </ItemGroup>

</Project>
