<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DeliverymanService\DeliverymanService.Domain\DeliverymanService.Domain.csproj" />
    <ProjectReference Include="..\..\VehicleService\VehicleService.Domain\VehicleService.Domain.csproj" />
  </ItemGroup>

</Project>
