<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeliverymanService\DeliverymanService.Domain\DeliverymanService.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared.Data\Shared.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Entities\**" />
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Entities\**" />
  </ItemGroup>

</Project>
