<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeliverymanService.Application\DeliverymanService.Application.csproj" />
    <ProjectReference Include="..\DeliverymanService.Domain\DeliverymanService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Remove="Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Data\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Data\**" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
